-- MySQL Script generated by MySQL Workbench
-- Thu Jun  9 14:51:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gestion-absences
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestion-absences
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestion-absences` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `gestion-absences` ;

-- -----------------------------------------------------
-- Table `gestion-absences`.`enseignants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-absences`.`enseignants` (
  `idEnseignants` INT NOT NULL,
  `NomEnseignants` VARCHAR(45) NOT NULL,
  `PrenomEnseignants` VARCHAR(45) NOT NULL,
  `EmailEnseignants` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEnseignants`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion-absences`.`groupe-etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-absences`.`groupe-etudiant` (
  `idGroupe-etudiant` INT NOT NULL,
  `nomGroupe-etudiant` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGroupe-etudiant`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion-absences`.`cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-absences`.`cours` (
  `idcours` INT NOT NULL,
  `TitreCours` VARCHAR(45) NOT NULL,
  `DateCours` DATE NOT NULL,
  `idEnseignants` INT NOT NULL,
  `DureeCours` VARCHAR(45) NOT NULL,
  `idGroupe` INT NOT NULL,
  PRIMARY KEY (`idcours`),
  INDEX `idEnseignants_idx` (`idEnseignants` ASC) VISIBLE,
  INDEX `idGroupe_idx` (`idGroupe` ASC) VISIBLE,
  CONSTRAINT `idEnseignants`
    FOREIGN KEY (`idEnseignants`)
    REFERENCES `gestion-absences`.`enseignants` (`idEnseignants`),
  CONSTRAINT `idGroupe-etudiant`
    FOREIGN KEY (`idGroupe`)
    REFERENCES `gestion-absences`.`groupe-etudiant` (`idGroupe-etudiant`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion-absences`.`etudiants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-absences`.`etudiants` (
  `idetudiants` INT NOT NULL,
  `NomEtudiants` VARCHAR(25) NOT NULL,
  `PrenomEtudiant` VARCHAR(25) NOT NULL,
  `EmailEtudiant` VARCHAR(45) NOT NULL,
  `idGroupeE` INT NOT NULL,
  `PhotoEtudiant` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idetudiants`),
  INDEX `idGroupe_idx` (`idGroupeE` ASC) VISIBLE,
  CONSTRAINT `idGroupe`
    FOREIGN KEY (`idGroupeE`)
    REFERENCES `gestion-absences`.`groupe-etudiant` (`idGroupe-etudiant`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gestion-absences`.`absences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-absences`.`absences` (
  `idAbsences` INT NOT NULL,
  `idEtudiants` INT NOT NULL,
  `idCours` INT NOT NULL,
  `JutsificationCours` TINYINT NOT NULL,
  `DocjustCours` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idAbsences`),
  INDEX `idEtudiants_idx` (`idEtudiants` ASC) VISIBLE,
  INDEX `idCours_idx` (`idCours` ASC) VISIBLE,
  CONSTRAINT `idCours`
    FOREIGN KEY (`idCours`)
    REFERENCES `gestion-absences`.`cours` (`idcours`),
  CONSTRAINT `idEtudiants`
    FOREIGN KEY (`idEtudiants`)
    REFERENCES `gestion-absences`.`etudiants` (`idetudiants`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

INSERT INTO `gestion-absences`.absences (idAbsences, idEtudiants, idCours, JutsificationCours, DocjustCours) VALUES (1, 1, 1, 1, 'rgerg');

INSERT INTO `gestion-absences`.`groupe-etudiant` (`idGroupe-etudiant`, `nomGroupe-etudiant`) VALUES (1, 'Flavio');
INSERT INTO `gestion-absences`.`groupe-etudiant` (`idGroupe-etudiant`, `nomGroupe-etudiant`) VALUES (2, 'Curry');

INSERT INTO `gestion-absences`.enseignants (idEnseignants, NomEnseignants, PrenomEnseignants, EmailEnseignants) VALUES (1, 'ttreger', 'zefzg', 'ergegerg');

INSERT INTO `gestion-absences`.cours (idcours, TitreCours, DateCours, idEnseignants, DureeCours, idGroupe) VALUES (1, 'zerge', '2022-06-14', 1, '3', 1);

INSERT INTO `gestion-absences`.etudiants (idetudiants, NomEtudiants, PrenomEtudiant, EmailEtudiant, idGroupeE, PhotoEtudiant) VALUES (1, 'Gacougnolle', 'Yassem', 'yassemgacougnollelebg', 1, 'texte');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;